[features]
seeds = false
skip-lint = false

[programs.localnet]
bonding_curve = "6WSsUceUttSpcy8P5ofy5cYDG6pyYLWRz3XTnx95EJWh"

[programs.devnet]
bonding_curve = "6WSsUceUttSpcy8P5ofy5cYDG6pyYLWRz3XTnx95EJWh"

[programs.mainnet]
bonding_curve = "6WSsUceUttSpcy8P5ofy5cYDG6pyYLWRz3XTnx95EJWh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
